apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true" 
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://smasher.shop"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: smasher.shop
    http:
      paths:
      - path:
        pathType: Prefix
        backend:
          service:
            name: topbeds-frontend-service
            port:
              number: 5173
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: topbeds-auth-service
            port:
              number: 3000
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: topbeds-user-service
            port:
              number: 3001
      - path: /api/property
        pathType: Prefix
        backend:
          service:
            name: topbeds-notification-service
            port:
              number: 3002
      - path: /api/booking
        pathType: Prefix
        backend:
          service:
            name: topbeds-course-service
            port:
              number: 3003
      - path: /api/chat
        pathType: Prefix
        backend:
          service:
            name: topbeds-payment-service
            port:
              number: 3004

